version: '3'

services:
  web:
    container_name: myriad-cms
    image: myriadsocial/myriad-cms
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    ports:
      - 80:80
    networks:
      myriad:
        ipv4_address: 172.27.1.5
        aliases:
          - myriad-cms

networks:
  myriad:
    external: true
