name: Main automation

on:
  push:
    branches:
      - main

concurrency:
  group: main-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest

    outputs:
      sha_short: ${{ steps.build-info.outputs.sha_short }}
      date: ${{ steps.build-info.outputs.date }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y%m%d')"

  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    needs: compute-build-info

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-main
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }}
            ${{ github.repository }}:latest-pre-alpha
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: [compute-build-info, build-and-publish-docker-image]
    env:
      DEPLOY: ${{ secrets.DEV_DEPLOY }}
    steps:
      - name: Checkout code
        if: "${{ env.DEPLOY == 'true' }}"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        if: "${{ env.DEPLOY == 'true' }}"
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.DEV_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get secrets
        if: "${{ env.DEPLOY == 'true' }}"
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            PORT:${{ secrets.DEV_GCP_PROJECT_ID }}/PORT
            REACT_APP_BASE_LAYOUT_CONFIG_KEY:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_BASE_LAYOUT_CONFIG_KEY
            REACT_APP_API_URL:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_API_URL
            REACT_APP_WEB_URL:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_WEB_URL
            REACT_APP_VERSION:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_VERSION
            REACT_APP_THEME_NAME:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_THEME_NAME
            REACT_APP_THEME_DEMO:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_THEME_DEMO
            REACT_APP_BOOTSTRAP_DOCS_LINK:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_BOOTSTRAP_DOCS_LINK
            REACT_APP_SASS_PATH:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_SASS_PATH
            REACT_APP_SASS_VARIABLES_PATH:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_SASS_VARIABLES_PATH
            REACT_APP_PURCHASE_URL:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_PURCHASE_URL
            REACT_APP_PREVIEW_URL:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_PREVIEW_URL
            REACT_APP_PREVIEW_REACT_URL:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_PREVIEW_REACT_URL
            REACT_APP_PREVIEW_DOCS_URL:${{ secrets.DEV_GCP_PROJECT_ID }}/REACT_APP_PREVIEW_DOCS_URL
            SSH_HOST:${{ secrets.DEV_GCP_PROJECT_ID }}/SSH_HOST
            SSH_USERNAME:${{ secrets.DEV_GCP_PROJECT_ID }}/SSH_USERNAME
            SSH_KEY:${{ secrets.DEV_GCP_PROJECT_ID }}/SSH_KEY
            SSH_PORT:${{ secrets.DEV_GCP_PROJECT_ID }}/SSH_PORT
      - name: Deploy
        if: "${{ env.DEPLOY == 'true' }}"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.secrets.outputs.SSH_HOST }}
          username: ${{ steps.secrets.outputs.SSH_USERNAME }}
          key: ${{ steps.secrets.outputs.SSH_KEY }}
          port: ${{ steps.secrets.outputs.SSH_PORT }}
          script: |
            helm repo add myriad https://charts.myriad.systems
            helm repo update
            helm upgrade myriad-cms myriad/myriad-cms \
              --install \
              --set-string image.tag=${{ needs.compute-build-info.outputs.sha_short }}-${{ needs.compute-build-info.outputs.date }} \
              --set-string config.port=${{ steps.secrets.outputs.PORT }} \
              --set-string config.appBaseLayoutConfigKey=${{ steps.secrets.outputs.REACT_APP_BASE_LAYOUT_CONFIG_KEY }} \
              --set-string config.appApiUrl=${{ steps.secrets.outputs.REACT_APP_API_URL }} \
              --set-string config.appWebUrl=${{ steps.secrets.outputs.REACT_APP_WEB_URL }} \
              --set-string config.appVersion=${{ steps.secrets.outputs.REACT_APP_VERSION }} \
              --set-string config.appThemeName=${{ steps.secrets.outputs.REACT_APP_THEME_NAME }} \
              --set-string config.appThemeDemo=${{ steps.secrets.outputs.REACT_APP_THEME_DEMO }} \
              --set-string config.appBootstrapDocsLink=${{ steps.secrets.outputs.REACT_APP_BOOTSTRAP_DOCS_LINK }} \
              --set-string config.appSassPath=${{ steps.secrets.outputs.REACT_APP_SASS_PATH }} \
              --set-string config.appSassVariablePath=${{ steps.secrets.outputs.REACT_APP_SASS_VARIABLES_PATH }} \
              --set-string config.appPurchaseUrl=${{ steps.secrets.outputs.REACT_APP_PURCHASE_URL }} \
              --set-string config.appPreviewUrl=${{ steps.secrets.outputs.REACT_APP_PREVIEW_URL }} \
              --set-string config.appPreviewReactUrl=${{ steps.secrets.outputs.REACT_APP_PREVIEW_REACT_URL }}\
              --set-string config.appPreviewDocsUrl=${{ steps.secrets.outputs.REACT_APP_PREVIEW_DOCS_URL }} \
              --set ingress.enabled=true \
              --set-string ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
              --set-string ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/limit-rps"="10" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/proxy-body-size"="100m" \
              --set-string ingress.annotations."nginx\.org/client-max-body-size"="100m" \
              --set-string ingress.hosts[0].host=cms.dev.myriad.systems \
              --set-string ingress.hosts[0].paths[0].path=/ \
              --set-string ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
              --set-string ingress.tls[0].secretName=myriad-cms-tls \
              --set-string ingress.tls[0].hosts[0]=cms.dev.myriad.systems \
              --set autoscaling.enabled=true
            kubectl rollout status deployment/myriad-cms
